---

clusterName: "fivex"
masterService: "fivex-master"
imageTag: "5.6.14"

extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-fivex-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-fivex-credentials
        key: username
